# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         EasyTool
version:      2006.06.13
version_from: EasyTool.pm
installdirs:  site
requires: 

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
